#!/usr/bin/env bash

print_info () {
    local result=$(dig "$1" +short)
    if [ -z "$result" ]; then
        echo "No information found for $1"
    else
        local type=$(dig "$1" +short | awk 'NR==1{print $2}')
        local target=$(dig "$1" +short | awk 'NR==1{print $1}')
        echo "The subdomain $1 is a $type record and points to $target"
    fi
}

if [ "$#" -eq 2 ]
then
    print_info "$2.$1"
elif [ "$#" -eq 1 ]
then
    echo "Please provide both subdomain and domain"
else
    print_info "www.$1"
    print_info "lb-01.$1"
    print_info "web-01.$1"
    print_info "web-02.$1"
fi
