#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Set custom HTTP response header in Nginx
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name _;

        add_header X-Served-By \$hostname;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        location / {
                try_files \$uri \$uri/ =404;
        }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
systemctl restart nginx
