#!/usr/bin/env bash

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
echo "
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
" > /etc/haproxy/haproxy.cfg

# Enable HAProxy service management via init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
service haproxy restart
