#!/usr/bin/env bash

# This script displays information about users in /etc/passwd using the while loop + IFS.

# Set the file path
file="/etc/passwd"

# Read the file line by line using a while loop
while IFS=: read -r username _ userid groupid _ info home shell
do
    # Extract user information from /etc/passwd
    # Assuming the password is stored in /etc/shadow, we'll use a placeholder for PASSWORD
    # You may need to adjust this part according to your system setup
    
    # Get the password from /etc/shadow
    password=$(grep "^$username:" /etc/shadow | cut -d ':' -f 2)
    
    # Print the user information
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
    echo
done < "$file"
