#!/usr/bin/env bash
# creates an RSA SSH key pair
# Define variables
key_name="school"
key_bits="4096"
passphrase="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -C "$key_name" -f "$key_name"
